"""empty message

Revision ID: 9a2ec8a55272
Revises: 
Create Date: 2023-10-10 17:18:21.233435

"""
from alembic import op
import sqlalchemy as sa
from app.models import environment, SCHEMA


# revision identifiers, used by Alembic.
revision = '9a2ec8a55272'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('firstname', sa.String(
                        length=40), nullable=False),
                    sa.Column('lastname', sa.String(
                        length=40), nullable=False),
                    sa.Column('email', sa.String(length=255), nullable=False),
                    sa.Column('username', sa.String(
                        length=40), nullable=False),
                    sa.Column('address', sa.String(
                        length=255), nullable=False),
                    sa.Column('city', sa.String(length=255), nullable=False),
                    sa.Column('state', sa.String(length=255), nullable=False),
                    sa.Column('country', sa.String(
                        length=255), nullable=False),
                    sa.Column('lat', sa.Float(), nullable=True),
                    sa.Column('lng', sa.Float(), nullable=True),
                    sa.Column('hashed_password', sa.String(
                        length=255), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('username')
                    )
    op.create_table('restaurants',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('ownerId', sa.Integer(), nullable=False),
                    sa.Column('address', sa.String(
                        length=255), nullable=False),
                    sa.Column('city', sa.String(length=255), nullable=False),
                    sa.Column('state', sa.String(length=255), nullable=False),
                    sa.Column('country', sa.String(
                        length=255), nullable=False),
                    sa.Column('lat', sa.Float(), nullable=True),
                    sa.Column('lng', sa.Float(), nullable=True),
                    sa.Column('name', sa.String(length=60), nullable=False),
                    sa.Column('type', sa.String(length=60), nullable=False),
                    sa.Column('image', sa.String(), nullable=True),
                    sa.Column('starRating', sa.Float(), nullable=True),
                    sa.Column('numReviews', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['ownerId'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('menuItems',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('restaurantId', sa.Integer(), nullable=True),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('type', sa.String(length=60), nullable=False),
                    sa.Column('image', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['restaurantId'], ['restaurants.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('reviews',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('userId', sa.Integer(), nullable=True),
                    sa.Column('restaurantId', sa.Integer(), nullable=True),
                    sa.Column('review', sa.String(), nullable=False),
                    sa.Column('stars', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['restaurantId'], ['restaurants.id'], ),
                    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('shoppingCarts',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('userId', sa.Integer(), nullable=True),
                    sa.Column('restaurantId', sa.Integer(), nullable=True),
                    sa.Column('total', sa.Float(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['restaurantId'], ['restaurants.id'], ),
                    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('shoppingCartItems',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('cartId', sa.Integer(), nullable=False),
                    sa.Column('menuItemId', sa.Integer(), nullable=False),
                    sa.Column('itemQuantity', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['cartId'], ['shoppingCarts.id'], ),
                    sa.ForeignKeyConstraint(
                        ['menuItemId'], ['menuItems.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###
    if environment == "production":
        op.execute(f"ALTER TABLE menuItems SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE restaurants SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE reviews SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE shoppingCarts SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE shoppingCartItems SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE users SET SCHEMA {SCHEMA};")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shoppingCartItems')
    op.drop_table('shoppingCarts')
    op.drop_table('reviews')
    op.drop_table('menuItems')
    op.drop_table('restaurants')
    op.drop_table('users')
    # ### end Alembic commands ###
